# Generated by Django 5.1.1 on 2024-10-04 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0003_alter_doctorprofile_age'),
        ('patient', '0002_alter_patientprofile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.IntegerField()),
                ('is_served', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientprofile')),
            ],
            options={
                'unique_together': {('doctor', 'token_number', 'created_at')},
            },
        ),
    ]
