# Generated by Django 5.1.1 on 2024-10-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
