# Generated by Django 5.1.1 on 2024-10-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctorprofile_age_alter_doctorprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
