# Generated by Django 5.1.1 on 2024-10-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_doctorprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='token_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
