# Generated by Django 5.1.1 on 2024-10-16 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_doctorprofile_token_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('hospital_picture', models.ImageField(blank=True, null=True, upload_to='hospital_pictures/')),
            ],
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='clinic_name',
        ),
        migrations.CreateModel(
            name='DoctorEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(blank=True, max_length=200, null=True)),
                ('dcotor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='doctor.doctorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('license_document', models.FileField(upload_to='doctor_licenses/')),
                ('verified_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='doctor.doctorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hospital_images/')),
                ('hospital_clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='doctor.hospitalclinic')),
            ],
        ),
    ]
