# Generated by Django 5.1.1 on 2024-10-17 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_doctorprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='hospital_clinic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.hospitalclinic'),
        ),
    ]
